Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1: Code-Review+1
> > 
> > Can you point to the sources of native layoutlib?  I could only find the Java versions.
> > 
> > What error do you get without compiler-rt?  Is there a function needed by layoutlib that's not provided by libgcc (which should already be included)?
> > 
> > Using compiler-rt is a move in the right direction - in the long run, we should build these with the toolchain (prebuilts/clang/host/linux-x86) instead of using this project which is mostly unmaintained.
> 
> For the moment, the code for native layoutlib lives in a separate branch: master-layoutlib-native, and the library that I have issues building there is libandroid-host (defined in frameworks/base/core/jni/Android.bp).
> My issue is in compiling android_graphics_ColorSpace.cpp. I get the following linker error:
> out/soong/.intermediates/frameworks/base/core/jni/libandroid-host/windows_x86_64_shared/obj/frameworks/base/core/jni/android_graphics_ColorSpace.o: In function `halfToFloat(unsigned short)':
> frameworks/base/core/jni/android_graphics_ColorSpace.cpp:46: undefined reference to `__gnu_h2f_ieee'
> I had that issue building on Linux already, which I solved by adding libcompiler_rt to my static_libs dependencies, and I need to have it compiled on Windows if I want to do the same.

Can you point me to whatever change you made here? I don't think adding libcompiler_rt explicitly like this is the correct solution. FWIW, we moved to libclang_rt.builtins (i.e. a newer version of compiler-rt) for Android Q, so this should be even less necessary.

Patch-set: 1
Reviewer: Gerrit User 1010056 <1010056@85c56323-6fa9-3386-8a01-6480fb634889>